# Generated by Django 5.2.12 on 2026-03-08 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('rejected', 'Rejected')], max_length=20)),
                ('table_tag_pose_json', models.TextField(blank=True, default='')),
                ('part_tag_pose_json', models.TextField(blank=True, default='')),
                ('robot_pos_json', models.TextField(blank=True, default='')),
                ('correction_x', models.FloatField(null=True)),
                ('correction_y', models.FloatField(null=True)),
                ('correction_z', models.FloatField(null=True)),
                ('correction_a', models.FloatField(null=True)),
                ('correction_b', models.FloatField(null=True)),
                ('correction_c', models.FloatField(null=True)),
                ('corrected_base_x', models.FloatField(null=True)),
                ('corrected_base_y', models.FloatField(null=True)),
                ('corrected_base_z', models.FloatField(null=True)),
                ('corrected_base_a', models.FloatField(null=True)),
                ('corrected_base_b', models.FloatField(null=True)),
                ('corrected_base_c', models.FloatField(null=True)),
                ('translation_mag', models.FloatField(null=True)),
                ('rotation_mag', models.FloatField(null=True)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='KRLProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('src_file', models.FileField(upload_to='krl_programs/')),
                ('dat_file', models.FileField(blank=True, null=True, upload_to='krl_programs/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('point_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_ip', models.GenericIPAddressField(default='192.168.1.120')),
                ('robot_port', models.IntegerField(default=54610)),
                ('camera_index', models.IntegerField(default=0)),
                ('camera_width', models.IntegerField(default=1280)),
                ('camera_height', models.IntegerField(default=720)),
                ('camera_fps', models.IntegerField(default=30)),
                ('camera_fx', models.FloatField(default=900.0)),
                ('camera_fy', models.FloatField(default=900.0)),
                ('camera_cx', models.FloatField(default=640.0)),
                ('camera_cy', models.FloatField(default=360.0)),
                ('dist_coeffs_json', models.TextField(default='[0,0,0,0,0]')),
                ('table_tag_id', models.IntegerField(default=0)),
                ('part_tag_id', models.IntegerField(default=1)),
                ('tag_size_mm', models.FloatField(default=100.0)),
                ('capture_joint_pos_json', models.TextField(default='[0, -90, 90, 0, 0, 0, 0, 0, 0, 0, 0, 0]')),
                ('nominal_base_x', models.FloatField(default=0.0)),
                ('nominal_base_y', models.FloatField(default=0.0)),
                ('nominal_base_z', models.FloatField(default=0.0)),
                ('nominal_base_a', models.FloatField(default=0.0)),
                ('nominal_base_b', models.FloatField(default=0.0)),
                ('nominal_base_c', models.FloatField(default=0.0)),
                ('nominal_part_tag_json', models.TextField(default='null')),
                ('hand_eye_matrix_json', models.TextField(default='null')),
                ('max_correction_mm', models.FloatField(default=50.0)),
                ('max_correction_deg', models.FloatField(default=5.0)),
                ('override_percent', models.IntegerField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='JobCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('calibrated', 'Calibrated'), ('running', 'Running'), ('completed', 'Completed'), ('aborted', 'Aborted'), ('error', 'Error')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('calibration', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.calibrationrecord')),
                ('krl_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.krlprogram')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='calibrationrecord',
            name='krl_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.krlprogram'),
        ),
    ]
