# Generated by Django 5.2.12 on 2026-03-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='aruco_dict_type',
            field=models.CharField(choices=[('DICT_4X4_250', '4x4 (250)'), ('DICT_5X5_250', '5x5 (250)'), ('DICT_6X6_250', '6x6 (250)'), ('DICT_7X7_250', '7x7 (250)')], default='DICT_5X5_250', max_length=20),
        ),
    ]
