# Generated by Django 5.2.12 on 2026-03-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_systemsettings_aruco_dict_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='aruco_dict_type',
            field=models.CharField(choices=[('DICT_4X4_50', '4x4 (50)'), ('DICT_4X4_100', '4x4 (100)'), ('DICT_4X4_250', '4x4 (250)'), ('DICT_4X4_1000', '4x4 (1000)'), ('DICT_5X5_50', '5x5 (50)'), ('DICT_5X5_100', '5x5 (100)'), ('DICT_5X5_250', '5x5 (250)'), ('DICT_5X5_1000', '5x5 (1000)'), ('DICT_6X6_50', '6x6 (50)'), ('DICT_6X6_100', '6x6 (100)'), ('DICT_6X6_250', '6x6 (250)'), ('DICT_6X6_1000', '6x6 (1000)'), ('DICT_7X7_50', '7x7 (50)'), ('DICT_7X7_100', '7x7 (100)'), ('DICT_7X7_250', '7x7 (250)'), ('DICT_7X7_1000', '7x7 (1000)')], default='DICT_6X6_250', max_length=20),
        ),
    ]
