# Generated by Django 5.2.12 on 2026-03-09 09:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_systemsettings_aruco_dict_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_number', models.IntegerField(default=1, help_text='KUKA $BASE number (1-32)')),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('z', models.FloatField(default=0.0)),
                ('a', models.FloatField(default=0.0)),
                ('b', models.FloatField(default=0.0)),
                ('c', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=False)),
                ('nominal_part_tag_json', models.TextField(default='null', help_text='Nominal part-to-table 4x4 matrix JSON')),
                ('hand_eye_matrix_json', models.TextField(default='null', help_text='Hand-eye calibration 4x4 matrix JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['base_number', 'name'],
            },
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='active_base_frame',
            field=models.ForeignKey(blank=True, help_text='Currently active base frame configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.baseframe'),
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('category', models.CharField(choices=[('robot', 'Robot'), ('calibration', 'Calibration'), ('camera', 'Camera'), ('job', 'Job'), ('settings', 'Settings'), ('system', 'System')], default='system', max_length=20)),
                ('message', models.CharField(max_length=500)),
                ('details_json', models.TextField(blank=True, default='{}')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'category'], name='core_eventl_timesta_04f940_idx')],
            },
        ),
    ]
