# Generated by Django 5.2.12 on 2026-03-09 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_baseframe_eventlog_activebase'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('joint_pos_json', models.TextField(default='[0, -90, 90, 0, 0, 0, 0, 0, 0, 0, 0, 0]', help_text='12 joint values: 6 robot axes + 6 external axes')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capture_positions', to='core.baseframe')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
