# Generated by Django 5.2.12 on 2026-03-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_capture_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fx', models.FloatField()),
                ('fy', models.FloatField()),
                ('cx', models.FloatField()),
                ('cy', models.FloatField()),
                ('dist_coeffs_json', models.TextField(help_text='Distortion coefficients JSON array')),
                ('rms_error', models.FloatField(help_text='RMS reprojection error')),
                ('num_poses', models.IntegerField(help_text='Number of calibration images used')),
                ('board_rows', models.IntegerField(default=9)),
                ('board_cols', models.IntegerField(default=6)),
                ('square_size_mm', models.FloatField(default=25.0)),
                ('is_applied', models.BooleanField(default=False, help_text='Whether this calibration has been applied to SystemSettings')),
                ('calibrated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-calibrated_at'],
            },
        ),
        migrations.AddField(
            model_name='calibrationrecord',
            name='is_dry_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='dry_run_mode',
            field=models.BooleanField(default=False, help_text='When true, calibration computes but does not send $BASE to robot'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='hsv_lower_json',
            field=models.TextField(default='[0, 0, 0]', help_text='Lower HSV bounds'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='hsv_upper_json',
            field=models.TextField(default='[180, 255, 255]', help_text='Upper HSV bounds'),
        ),
    ]
