# Generated by Django 5.2.12 on 2026-03-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_camera_cal_hsv_dryrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcycle',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
