#ifndef GLOBAL_H
#define GLOBAL_H

#define SELECT_CURRENT_PANEL_ZERO 0
#define SELECT_VOLTAGE_PANEL_ZERO 4
#define SELECT_CURRENT_PANEL_ONE 1
#define SELECT_VOLTAGE_PANEL_ONE 5
#define SELECT_CURRENT_PANEL_TWO 2
#define SELECT_VOLTAGE_PANEL_TWO 6
#define SELECT_CURRENT_PANEL_THREE 3
#define SELECT_VOLTAGE_PANEL_THREE 7

#endif // GLOBAL_H