class Command:
    CMD_GET_PROGRAM_INFO = b"getprograminfo;"
    CMD_GET_ROBOT_NAME = b"getrobotname;"
    CMD_GET_ROBOT_TYPE = b"getrobottype;"
    CMD_GET_NUM_ROBOT_AXES = b"getnumrobotaxes;"
    CMD_GET_ROBOT_SERIAL_NUM = b"getrobotserialnum;"
    CMD_GET_SOFTWARE_VERSION = b"getsoftwareversion;"
    CMD_GET_EXTERNAL_AXES = b"getnumexternalaxes;"
    CMD_GET_GO_TO_JOINT_POS = b"gotojointpos;"
    CMD_GET_ABS_ACCUR_STATUS = b"getabsaccurstatus;"
    CMD_SET_HOME = "sethome"
    CMD_GO_TO_JOINT_POS = "gotojointpos"
    CMD_GET_POS_JNT_LIM = b"getposjntlim;"
    CMD_GET_NEG_JNT_LIM = b"getnegjntlim;"
    CMD_IS_HOME = b"ishome;"
    CMD_SET_BASE_DATA="setbasedata"
    CMD_SET_TOOL_DATA="settooldata"
    CMD_GET_CURRENT_JOINTS = b"getcurrentjoints;"
    CMD_GET_CURRENT_POS = b"getcurrentpos;"
    CMD_GO_TO_CART_POS = "gotocartpos"
    CMD_GO_TO_FRAME = "gotoframe"
    CMD_GET_BASE_DATA = b"getbasedata;"
    CMD_GET_TOOL_DATA = b"gettooldata;"
    CMD_GET_LOAD_DATA = b"getloaddata;"
    CMD_GET_OPERATING_MODE = b"getoperatingmode;"
    CMD_GET_OVERRIDE = b"getoverride;"
   